### ISSUE TITLE
Make the AI independent of the side we play on

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyAI#260]
I have suggested to use a "change_reference" method in the tracker to reversed the position of the object according to a constant in the config. This will allowed the AI to assume our team is always on the positive x half of the field and simplify the test of tactic.

**Comment by sim0504** [comment]
One probleme is to sync the UI-Debug with the reversing of the field and the target sent to the AI when testing. We could add this to the shared config.

**Comment by sim0504** [comment]
```
[COMMUNICATION]
referee_udp_address = 224.5.23.1
referee_port=10023
vision_udp_address = 224.5.23.2
vision_port=10227
>>>Added
[FIELD]
reversed={False,True}
```

**Comment by PhiBabin** [comment]
#374
