### ISSUE TITLE
Send the ball's new position to the strategy in _select_next_state

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyAI#304]
> ./ai/Algorithm/auto_play.py:133:                RefereeCommand.BALL_PLACEMENT_US: SimpleAutoPlayState.HALT, #TODO send ball new position to strategy...

The problem: The ball position should be sent to the strategy.

**Comment by sim0504** [comment]
is this still valid?

**Comment by PhiBabin** [comment]
I have no idea what this is...

**Comment by PhiBabin** [comment]
Ok, it's a thing todo for next year
