### ISSUE TITLE
Repair and complete methods in referee.py

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyAI#309]
> ./ai/GameDomainObjects/referee.py:137:    # TODO

The problem: The following fucntions are commanded out and should either be repaired or removed:
- [ ] _convert_raw_to_us
- [ ] _convert_raw_to_them
- [ ] _is_our_team_command
- [ ] _is_yellow_command
- [ ] _is_blue_command

**Comment by sim0504** [comment]
Fixed in #334
