### ISSUE TITLE
Change the Offense_3v3 IDs to make them dynamic

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyAI#321]
> ./ai/STA/Strategy/offense_3v3.py:20:        # TODO: HARDCODED ID FOR QUALIFICATION, REMOVE LATER

The current version of the strategy uses hardcoded IDs to execute the strategy. This should be changed to make it useful in real games.

**Comment by PhiBabin** [comment]
Too simulare to #230
