### ISSUE TITLE
Iterate over game_state.RoleMapping instead of Role in exec, in strategy.py

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyAI#323]
> ./ai/STA/Strategy/strategy.py:90:        # TODO We should probably iterate over game_state.RoleMapping instead of Role
> ./ai/STA/Strategy/strategy.py:91:        # TODO It would allow us to deal with fewer than 6 roles

The problem: The current loop is made in role, this could be replaced with an iteration over RoleMapping, thus reducing the number of roles to deal with.

**Comment by PhiBabin** [comment]
It does not really change anything either way a check if made in player is none
