### ISSUE TITLE
Add logic to take the opponent players' position, and the ball speed, in goalkeeper.py

### ISSUE THREAD

**Issue by frstp64** [RoboCupULaval/StrategyAI#324]
> ./ai/STA/Tactic/goalkeeper.py:36:    # TODO: À complexifier pour prendre en compte la position des joueurs adverses et la vitesse de la balle.

The current goalkeeper tactic does not take some useful information into account when trying to block the ball. This would be a great enhancement.

**Comment by PhiBabin** [comment]
done
