### ISSUE TITLE
Le controle du robot est GRANDEMENT affecté par les performances dun ordi

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/StrategyAI#343]
On soupconne que ca l'à avoir avec la reception/traitement des frames de vision.

**Comment by sim0504** [comment]
Je propose de logger le temps d'execution de certaines fonctions dans le code.

- [ ] Calcul du path
- [ ] Update des KalmanFilter
- [ ] Prediciton des KalmanFilter
- [ ] Execution du VelocityRegulator
- [ ] Envoi des commandes aux robots

**Comment by sim0504** [comment]
Aussi, logger les fps de la vision.

**Comment by frstp64** [comment]
Méthode suggérée: utiliser les outils de python faits pour faire du profilage sur le cpu time au lieux du clock time.

#344 pour référence

**Comment by PhiBabin** [comment]
On pourrait essayer de calculé c'est quoi la latence du système. Comme cela on aurait deux indices sur la performance de l'IA.

**Comment by sim0504** [comment]
Le profiling est foncitonnel sur dev. On va pouvoir tester ca.
