### ISSUE TITLE
kick command not working dans le vrai de vrai monde

### ISSUE THREAD

**Issue by wonwon0** [RoboCupULaval/StrategyAI#357]
le robot kick pas quand on test real-life.

**Comment by wonwon0** [comment]
dans la branche dev

**Comment by PhiBabin** [comment]
Causé par un delete accidentelle:
https://github.com/RoboCupULaval/StrategyAI/commit/b272478f3e4acba25f3a15b81a28f27676b93a83#diff-587b489ef6447ea43d9be2b4b4d0b4bfL22

**Comment by sim0504** [comment]
va etre fix quand on va merge la PR #351
