### ISSUE TITLE
Add collision zone

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#370]
A player should be able to enter the goal area of the opposite team. Currently they can enter it.

**Comment by wonwon0** [comment]
And thus was the initial purpopse of the collision_body

**Comment by sim0504** [comment]
C'était rendu impossible à supporter. Un changement était nécessaire pour le futur.

**Comment by sim0504** [comment]
J'ai commencé ;a faire le typing des obstacles (#feature/add_obstacles_type)

**Comment by sim0504** [comment]
Il reste juste à determiner le avoid_dir pour les goals afin que le robot essaye pas de faire le tour du mauvais coté et à ajouter les constantes de field dans la creation de l'obstacle

**Comment by PhiBabin** [comment]
Ouin, il faudrait refaire les constantes de field des goals et recheck tous les endroits dans le code qui assume un cercle. Ce ne sera pas une mince affaire...

**Comment by sim0504** [comment]
Il faut quand meme les scaler en fonction du terrain

**Comment by wonwon0** [comment]
Ça sera pas si pire, la plus grosse job serait de dealer ak dautre geometries

**Comment by wonwon0** [comment]
Mon approche serait de faires une approximation ak des cercles pour avoir de quoi de fonctionnel, pis apres on inplemente les carrés si on a le temps

**Comment by wonwon0** [comment]
javais pas lu que t'avais commencé a travailler dessus ca, sorry jme suis un-assign

**Comment by wonwon0** [comment]
#403 , moi et simon on a déterminer que c'était pas nécessaire, on a juste a faire en sorte qu'aucun go_kick est commandé quand la ball est dans their_goal et que juste le goal_keeper ce fait demander de go_kick quand la balle est dans our_goal
