### ISSUE TITLE
Adapt Grsim to the rules of division B

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#376]
Currently the configuration of Grsim is made for division A. There was commit on the GrSim repo to handle switching between divisions, but it was removed. There currently an issue on the official repo, but it was not fixed: https://github.com/RoboCup-SSL/grSim/issues/66

**Comment by PhiBabin** [comment]
Pull request done, you can use it while we wait for a merge: https://github.com/RoboCup-SSL/grSim/pull/68

**Comment by PhiBabin** [comment]
The official repo has merge the pull request.

**Comment by wonwon0** [comment]
Such proud, many robocup, very code

**Comment by sim0504** [comment]
@PhiBabin  ta prochaine issu a détruire: https://github.com/RoboCup-SSL/grSim/issues/39

**Comment by PhiBabin** [comment]
Wtf, il y a genre 3 PR aucune de mergé tous au tours de l'overlap.
