### ISSUE TITLE
Rajouté un comportement au goalkeeper pour tir de pénalité

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#395]
Le goalkeeper présentement ignore le flag `penalty_kick`, il devrait avoir un comportement plus spécialisé à celui d'un tir de pénalité.

**Comment by sim0504** [comment]
Déjà rester en avant au centre serait pas pire

**Comment by wonwon0** [comment]
i'm on it.

**Comment by wonwon0** [comment]
#409

**Comment by wonwon0** [comment]
rekt by #409
