### ISSUE TITLE
Assuré que l'IA respecte les règles de Robocup SSL 2018

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#398]
Il est important que notre IA respecte les règles du jeu pour évité des cartons jaunes/rouges. Il faudrait donc que soit en passe à travers les règles ou que l'on teste avec un autoref. 
Je n'ai pas encore réussie à faire marché un autoref avec notre IA.
Présentement voici la liste des règles que l'on désobéit:

- [x] Les robots rentrent dans la zone des buts adverses.
- [x] Le indirect kick peut kicker dans le but adverse
- [x] Lors d'un kick directe et indirecte l'équipe averse ne peut pas être à moins de 500mm de la balle, tant qu'elle n'a pas été kicker
- [x] "If, at the time the ball enters play, a member of the kicker’s team occupies the area closer than
200 mm to the opponent’s defence area"

**Comment by sim0504** [comment]
Lors d'un but, nos robots foncent vers l’intérieur du but. Je crois qu'il y a une tactic qui assign encore des positions à des endroits illégals

**Comment by PhiBabin** [comment]
Ouin, je pense que c'est cause par ce que techniquement le goal_area n'incluent pas l'intérieur du but. Anyway en game le Play est stop si la balle rentre dans le but

**Comment by PhiBabin** [comment]
On a eu zero carton jaune, fecque je pense que l'on respecte les règles...

**Comment by PhiBabin** [comment]
C'était pourquoi déjà?

**Comment by wonwon0** [comment]
((((((Optionnal))))))

**Comment by sim0504** [comment]
too many defender in defence area mais c'était un edge case les robots etaient tous en tas devant le but.
