### ISSUE TITLE
Fix position for pass

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#399]
`position_for_pass` est une grosse boîte noir avec beaucoup trop d'offset et de padding magique. De plus, il a des versions field positif et négatif de tous.
La plupart des positions calculé pour les joueurs ne sont même pas sur le terrain de jeu!

**Comment by wonwon0** [comment]
force field method

**Comment by wonwon0** [comment]
J'ai déjà implement ca quick dans ma maitrise: (matlab code of course)

https://github.com/wonwon0/matlab_stuff/blob/master/rrr%20version%20phil%20v3/verifVitesse_ForceField.m

**Comment by PhiBabin** [comment]
#408
