### ISSUE TITLE
La force du kick de go_kick devrait être fonction de la distance

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#406]
Il serait utile que go_kick est un flag pour qu'il décide automatiquement la force du kick en fonction de la distance de la cible.

**Comment by PhiBabin** [comment]
Genre

**Comment by sim0504** [comment]
Ca serait bcp plus simple que l'enum du kick force contient une fonction static qui retourne un state selon la distance donné en paramètre

**Comment by sim0504** [comment]
Sinon on enlève la kickforce et on passe la distance en paramètre directement

**Comment by sim0504** [comment]
Par contre, ca va etre ultra variable la distance, tandis que la force est plus constante

**Comment by PhiBabin** [comment]
Ouin lidee est que tu as besoin de la distance uniquement pour une passe et donc tu veux upper bound distance. Ce n'est pas grave  de tire pas assez  loin lors d'une  passe. Lors d'un  tir au but on veut tiré à puissance max.

**Comment by sim0504** [comment]
on peut faire des états plus utile genre SHORT_PASS, LONG_PASS, BUMP, GOALKICK

**Comment by PhiBabin** [comment]
Sa revien au même que d'avoir des LOW, MEDIUM et HIGH kick faire cela. C'est pour cela l'idée d'une valeur analogique, au lieu de discrète

**Comment by PhiBabin** [comment]
Finalement, il a été décidé que tous les kicks au goal seront à max kick. Dépend de la distance de la passe le kick serait faible ou moyen

**Comment by PhiBabin** [comment]
#474
