### ISSUE TITLE
Rajouté une option pour ignoré les balls sur côté de terrain

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#412]
En compétition, le temps avec un terrain est précieux. C'est pourquoi il arrive souvent que deux équipes débug sur le même terrain, le problème avec deux équipes sur le même terrain s'est 2 balles sur le même terrain. Il est donc utile d'avoir un option dans l'IA pour _filter out_ la balle du côté positif du terrain ou du côté négatif.

**Comment by sim0504** [comment]
Je vais travailler la dessus

**Comment by PhiBabin** [comment]
Sur les outils de TIGERS, ils appellent cette option 'camera filtering'

**Comment by sim0504** [comment]
Fonctionne sur multiball. Pas encore push. On peut désactiver les caméras qu'on veut pas

**Comment by sim0504** [comment]
C'est push. J'ai pas vraiment fait un filtre spécifique pour les cotés du terrain, mais ca revient au meme. Si il y a une rogue ball qui se promène, elle va être considérer comme une nouvelle balle. On peut aussi desactiver les cameras avec leur id: `disabled_camera=[0,1,2,3]` dans le fichier de config

**Comment by sim0504** [comment]
#426
