### ISSUE TITLE
autoplay should switch to a safe state when less than 3 robots are visible

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#427]
Currently, autoplay crash we don't have the minimum number of robots. It would be preferable if it fall back to safe state while it's waiting for 3 robots to appear.

**Comment by sim0504** [comment]
We could have a strategy which only use 1 or 2 robots when we don't have enough robot on the field.

**Comment by PhiBabin** [comment]
Yeah that what time mean by safe strategy

**Comment by PhiBabin** [comment]
done #433
