### ISSUE TITLE
Le contrôleur en vélocité arrête trop tôt à bas fps

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#432]
Avec un fps dengine en dessous de 70 fps, dans la vraie vie, le contrôleur en vitesse va arrêter trop tôt ( 50cm ) avant sa destination.

**Comment by sim0504** [comment]
Qu'est ce que tu veux dire? les commandes ne sont plus envoyé? le controlleur est reset? le controlleur ne s'exécute plus?

**Comment by PhiBabin** [comment]
Le robot arrête à 50cm de la target. Le controler envoie un vitesse 0 quand il devrait envoyer une vitesse non-nulle.

**Comment by wonwon0** [comment]
honetement fuck les bas fps

**Comment by wonwon0** [comment]
maudite populace

**Comment by sim0504** [comment]
Probablement que l'estimation de la vitesse est moins bonne. Faudrait tester avec un graph

**Comment by PhiBabin** [comment]
Après des tests l'emergency break cause le bug: https://github.com/RoboCupULaval/StrategyAI/blob/dev/Engine/regulators/velocity_regulators.py#L37

**Comment by sim0504** [comment]
En simulation je roule parfaitement à 20Hz. Probablement que le vrai robot freine bcp plus vite.

**Comment by PhiBabin** [comment]
En simulation aussi il le fait. Il ne le fait pas tout le temps

**Comment by sim0504** [comment]
J'ai fait beaucoup de test sur mon ordi et j'ai jamais vu ca à 20fps. c'est un nouveau problème donc?

**Comment by sim0504** [comment]
seems to be solve afaik
