### ISSUE TITLE
La referee queue ne se vide pas assez vite

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyAI#437]
Le referee envoit plus vite que 10Hz et la queue semble overflow:

`[DEBUG] - RefereeReceiver       : Queue is at 100% of it's max capacity.`

**Comment by PhiBabin** [comment]
Est-ce que tu run en autonomous mode? Parce que le referee receiver a sa queue vidé uniquement en autonomous mode

**Comment by sim0504** [comment]
Oui je suis en compétition mode. Mais ca arrive seulement au début de temps en temps. Mais on perd quand meme des packets du referee ca veut dire

**Comment by sim0504** [comment]
Le problème etait le sleep(3) avant que le coach commence. Le bug va donc etre fixed avec le nouveau role_mapper.
