### ISSUE TITLE
Le robot a tendance à Bump la balle en simulation au lieu de la kick

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#440]

**Comment by PhiBabin** [comment]
L'autoref détecte cela comme du double touch, donc tous nos direct kick fail

**Comment by sim0504** [comment]
causé par un controle trop agressif a bas fps

**Comment by PhiBabin** [comment]
Est-ce que c'est encore présent?

**Comment by sim0504** [comment]
oui car si je change anything ca va etre rechanhé...
