### ISSUE TITLE
Lors d'un Kickoff, les robots defensifs ne peuvent pas s'approché de la balle avant qu'elle soit frappé

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#450]
Le bug est dans la transition de kickoff -> normal. Il faudrait que quand il switch a normal, il y est une stratégie temporaire(defenseWallNokick) qui embarque en attendant que le robot offensif kick la balle.

**Comment by sim0504** [comment]
• the robot taking the kickoff is allowed to leave its own half of the field, as long as this robot
stays within the center circle and no other robot touches the ball

**Comment by sim0504** [comment]
• all robots are in their own half of the field

**Comment by PhiBabin** [comment]
#471
