### ISSUE TITLE
Ball placement fail à cause que le pathfinder lui fait évité les obstacles

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#452]
Une solution serait de pouvoir passer un flag au pathfinder pour qu'il ignore les obstacles.

**Comment by sim0504** [comment]
en gros, on bypass le pathfinder. le retour du fameux `patherfinder=False` ?

**Comment by PhiBabin** [comment]
Genre

**Comment by sim0504** [comment]
fix in #461
