### ISSUE TITLE
Lors d'un tir indirect ou direct, le position for pass ne vas pas être nécessairement du bon coté

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#462]
Il faudrait que position for pass offense soit fait par un seul des deux attaquants et que le FIRST_ATTACK kick toujours.

**Comment by PhiBabin** [comment]
Aussi lors d'un indirect/direct dans le coté ennemie seulement les deux attaquant sont dans la zone ennemie

**Comment by sim0504** [comment]
Je ne suis pas sur de bien comprendre l'issu

**Comment by PhiBabin** [comment]
Les positions for pass force un robot dans une area. S'il y a deux passeur, la zone offensive est séparé en deux area (haut et bas). Le passeur du haut doit faire le kick indirecte dans zone du bas, il va y avoir deux robots dans la zone du bas

**Comment by PhiBabin** [comment]
#481
