### ISSUE TITLE
Les membres du wall ne devrait aller kicker la balle si un robot ennemie a la balle

### ISSUE THREAD

**Issue by PhiBabin** [RoboCupULaval/StrategyAI#470]

**Comment by wonwon0** [comment]
hemm well, ca se produitquand cette affaire la en auto play?
parce que les membres de defensewall se fait meme pas donner la node go_kick...

**Comment by wonwon0** [comment]
oin mais yer juste donner aux attackers

**Comment by PhiBabin** [comment]
Non, je parle dans `align_to_defense_wall`, la tactic. 
Elle appel go_kick. Tactic inside another tactic

**Comment by PhiBabin** [comment]
#482
