### ISSUE TITLE
fix the watchdog

### ISSUE THREAD

**Issue by sim0504** [RoboCupULaval/StrategyAI#498]
Sometime, the watchdog doesn't kill the coach or engine process and 2 of them are alive at the same time.

**Comment by PhiBabin** [comment]
This is fixed. Now the referee receiver seem to be the problem. I think that he is not terminate, since it's printing. 
Log files are here: https://drive.google.com/open?id=13A2NGy4FdSVAq37YrJaLFWDW7_EVVmcF
